from dataclasses import dataclass
from typing import List

from compiler.ir import IRProgram

# ==========================================
# Bytecode Opcodes
# ==========================================

OP_MOVE = 1
OP_TURN = 2


# Direction codes
DIR_LEFT = 1
DIR_RIGHT = 2


# ==========================================
# Bytecode Program
# ==========================================


@dataclass
class BytecodeProgram:

    instructions: List[int]

    def __str__(self):

        if not self.instructions:
            return "(empty bytecode)"

        return " ".join(str(value) for value in self.instructions)


# ==========================================
# Code Generator
# ==========================================


class CodeGenerator:

    def generate(self, ir_program):

        if not isinstance(ir_program, IRProgram):
            raise TypeError("Code Generator expected an IRProgram.")

        bytecode = []

        for instruction in ir_program.instructions:

            # ------------------------------
            # MOVE
            # ------------------------------

            if instruction.opcode == "MOVE":

                bytecode.append(OP_MOVE)
                bytecode.append(instruction.operand)

            # ------------------------------
            # TURN
            # ------------------------------

            elif instruction.opcode == "TURN":

                bytecode.append(OP_TURN)

                if instruction.operand == "LEFT":
                    bytecode.append(DIR_LEFT)

                elif instruction.operand == "RIGHT":
                    bytecode.append(DIR_RIGHT)

                else:
                    raise ValueError(f"Invalid direction: " f"{instruction.operand}")

            else:

                raise ValueError(f"Unknown IR opcode: " f"{instruction.opcode}")

        return BytecodeProgram(bytecode)


# ==========================================
# Test
# ==========================================

if __name__ == "__main__":

    from compiler.lexer import Lexer
    from compiler.parser import Parser
    from compiler.semantic import SemanticAnalyzer
    from compiler.ir import IRGenerator

    source = """
    START

    MOVE 100
    TURN RIGHT
    MOVE 50
    TURN LEFT
    MOVE 30

    STOP
    """

    try:

        # 1. Lexer
        lexer = Lexer(source)
        tokens = lexer.tokenize()

        print("✓ Lexical Analysis Successful")

        # 2. Parser
        parser = Parser(tokens)
        program = parser.parse()

        print("✓ Syntax Analysis Successful")

        # 3. Semantic Analysis
        analyzer = SemanticAnalyzer()
        analyzer.analyze(program)

        print("✓ Semantic Analysis Successful")

        # 4. IR Generation
        ir_generator = IRGenerator()
        ir_program = ir_generator.generate(program)

        print("✓ IR Generation Successful")

        print("\nIR:")
        print("--------------------------------")
        print(ir_program)

        # 5. Code Generation
        code_generator = CodeGenerator()
        bytecode = code_generator.generate(ir_program)

        print("\n✓ Code Generation Successful")

        print("\nGenerated Bytecode:")
        print("--------------------------------")
        print(bytecode)

    except Exception as error:

        print(f"\n❌ Error: {error}")
